name: GitHub CI

on: push

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v4
      - name: Install Debian packages
        run: |
          sudo apt-get update
          sudo apt-get install -y bash gawk grep wget
      - name: Tests
        run: |
          cd $GITHUB_WORKSPACE
          ./continuous-integration/bashlint.sh
          ./continuous-integration/update-check-no-op.sh
          ./continuous-integration/update-check-forced-update.sh
          echo "All tests passed. Have a nice day."
